# theory 
# --------------
# IN prev file , for the chatbot to know the history we maintained a list known as chat history
# where the list contains all the convo between me and chatbot 
# but as the list getting big , its hard for chatbot to know which text is of user and which is generated by itself 
# so for this langchain introduced different messages 

# system messages : message at the start 
# human message 
# Ai message 


# we will use the messages in updated chatbot 

from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint

llm = HuggingFaceEndpoint(
    repo_id= "HuggingFaceTB/SmolLM3-3B", 
    task = "text-generation"
)

model = ChatHuggingFace(llm = llm , verbose = False)

messages = [
    SystemMessage(content = "You are helpful assistant"),
    HumanMessage(content = "Tell me about langchain")
]

result = model.invoke(messages)

messages.append(AIMessage(content = result.content))

print(messages)